//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tinhke
    {
        public int id { get; set; }
        public int idtinhdau { get; set; }
        public int idtinhcuoi { get; set; }
    
        public virtual tinh tinh { get; set; }
        public virtual tinh tinh1 { get; set; }
    }
}
